version: "3.7"
services:
  database:
    image: postgres:9.4
    volumes:
      - type: volume
        source: alp-dbdata
        target: /var/lib/postgresql/data
      - "confluence/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh"
      - "tmp:/tmp/dumps"
    environment:
      - POSTGRES_PASSWORD=postgres            
  nginx:
    build: ./nginx
    user: "root"
    depends_on:
      - confluence
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
  confluence:
    build:
      context: ./confluence
      dockerfile: Dockerfile
      args:
        buildno: 1
    depends_on:
      - database
    links:
      - database
    volumes:
      - type: volume
        source: confluence_home
        target: /opt/confluence-home
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_JDBC_URL=jdbc:postgresql://database:5432     
volumes:
  alp-dbdata:
  confluence_home: {}